### ISSUE TITLE
Initialise Discord bot and let it start listening to messages

### ISSUE THREAD

**Issue by zz-hh-aa** [fac30/discord-ai-bot--kieran-ollie#4]
# User stories
As a back-end developer, I want to initialise my Discord bot and log in to Discord using the new `Discord.Client()` constructor and `client.login` method with my Discord token, to start listening for messages.

# To-do
- [ ] Use `Discord.Client()`
- [ ] User `client.login` method 
- [ ] Enable necessary permissions in OAuth2
